// Generated by gencpp from file pick_objects/PlaceBox.msg
// DO NOT EDIT!


#ifndef PICK_OBJECTS_MESSAGE_PLACEBOX_H
#define PICK_OBJECTS_MESSAGE_PLACEBOX_H

#include <ros/service_traits.h>


#include <pick_objects/PlaceBoxRequest.h>
#include <pick_objects/PlaceBoxResponse.h>


namespace pick_objects
{

struct PlaceBox
{

typedef PlaceBoxRequest Request;
typedef PlaceBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaceBox
} // namespace pick_objects


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_objects::PlaceBox > {
  static const char* value()
  {
    return "4f4d1ddc81d0c0808876510a339bea29";
  }

  static const char* value(const ::pick_objects::PlaceBox&) { return value(); }
};

template<>
struct DataType< ::pick_objects::PlaceBox > {
  static const char* value()
  {
    return "pick_objects/PlaceBox";
  }

  static const char* value(const ::pick_objects::PlaceBox&) { return value(); }
};


// service_traits::MD5Sum< ::pick_objects::PlaceBoxRequest> should match 
// service_traits::MD5Sum< ::pick_objects::PlaceBox > 
template<>
struct MD5Sum< ::pick_objects::PlaceBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_objects::PlaceBox >::value();
  }
  static const char* value(const ::pick_objects::PlaceBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_objects::PlaceBoxRequest> should match 
// service_traits::DataType< ::pick_objects::PlaceBox > 
template<>
struct DataType< ::pick_objects::PlaceBoxRequest>
{
  static const char* value()
  {
    return DataType< ::pick_objects::PlaceBox >::value();
  }
  static const char* value(const ::pick_objects::PlaceBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_objects::PlaceBoxResponse> should match 
// service_traits::MD5Sum< ::pick_objects::PlaceBox > 
template<>
struct MD5Sum< ::pick_objects::PlaceBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_objects::PlaceBox >::value();
  }
  static const char* value(const ::pick_objects::PlaceBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_objects::PlaceBoxResponse> should match 
// service_traits::DataType< ::pick_objects::PlaceBox > 
template<>
struct DataType< ::pick_objects::PlaceBoxResponse>
{
  static const char* value()
  {
    return DataType< ::pick_objects::PlaceBox >::value();
  }
  static const char* value(const ::pick_objects::PlaceBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_OBJECTS_MESSAGE_PLACEBOX_H
