// Generated by gencpp from file pick_objects/PlaceBoxResponse.msg
// DO NOT EDIT!


#ifndef PICK_OBJECTS_MESSAGE_PLACEBOXRESPONSE_H
#define PICK_OBJECTS_MESSAGE_PLACEBOXRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_objects
{
template <class ContainerAllocator>
struct PlaceBoxResponse_
{
  typedef PlaceBoxResponse_<ContainerAllocator> Type;

  PlaceBoxResponse_()
    : rep_info()  {
    }
  PlaceBoxResponse_(const ContainerAllocator& _alloc)
    : rep_info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rep_info_type;
  _rep_info_type rep_info;





  typedef boost::shared_ptr< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlaceBoxResponse_

typedef ::pick_objects::PlaceBoxResponse_<std::allocator<void> > PlaceBoxResponse;

typedef boost::shared_ptr< ::pick_objects::PlaceBoxResponse > PlaceBoxResponsePtr;
typedef boost::shared_ptr< ::pick_objects::PlaceBoxResponse const> PlaceBoxResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_objects::PlaceBoxResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pick_objects

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c052bddbf855bdd6b0c6aa0a0c252c2";
  }

  static const char* value(const ::pick_objects::PlaceBoxResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c052bddbf855bddULL;
  static const uint64_t static_value2 = 0x6b0c6aa0a0c252c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_objects/PlaceBoxResponse";
  }

  static const char* value(const ::pick_objects::PlaceBoxResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string rep_info\n\
\n\
";
  }

  static const char* value(const ::pick_objects::PlaceBoxResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rep_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaceBoxResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_objects::PlaceBoxResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_objects::PlaceBoxResponse_<ContainerAllocator>& v)
  {
    s << indent << "rep_info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rep_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_OBJECTS_MESSAGE_PLACEBOXRESPONSE_H
