// Generated by gencpp from file pick_objects/RemoveBox.msg
// DO NOT EDIT!


#ifndef PICK_OBJECTS_MESSAGE_REMOVEBOX_H
#define PICK_OBJECTS_MESSAGE_REMOVEBOX_H

#include <ros/service_traits.h>


#include <pick_objects/RemoveBoxRequest.h>
#include <pick_objects/RemoveBoxResponse.h>


namespace pick_objects
{

struct RemoveBox
{

typedef RemoveBoxRequest Request;
typedef RemoveBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveBox
} // namespace pick_objects


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_objects::RemoveBox > {
  static const char* value()
  {
    return "4f4d1ddc81d0c0808876510a339bea29";
  }

  static const char* value(const ::pick_objects::RemoveBox&) { return value(); }
};

template<>
struct DataType< ::pick_objects::RemoveBox > {
  static const char* value()
  {
    return "pick_objects/RemoveBox";
  }

  static const char* value(const ::pick_objects::RemoveBox&) { return value(); }
};


// service_traits::MD5Sum< ::pick_objects::RemoveBoxRequest> should match 
// service_traits::MD5Sum< ::pick_objects::RemoveBox > 
template<>
struct MD5Sum< ::pick_objects::RemoveBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_objects::RemoveBox >::value();
  }
  static const char* value(const ::pick_objects::RemoveBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_objects::RemoveBoxRequest> should match 
// service_traits::DataType< ::pick_objects::RemoveBox > 
template<>
struct DataType< ::pick_objects::RemoveBoxRequest>
{
  static const char* value()
  {
    return DataType< ::pick_objects::RemoveBox >::value();
  }
  static const char* value(const ::pick_objects::RemoveBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_objects::RemoveBoxResponse> should match 
// service_traits::MD5Sum< ::pick_objects::RemoveBox > 
template<>
struct MD5Sum< ::pick_objects::RemoveBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_objects::RemoveBox >::value();
  }
  static const char* value(const ::pick_objects::RemoveBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_objects::RemoveBoxResponse> should match 
// service_traits::DataType< ::pick_objects::RemoveBox > 
template<>
struct DataType< ::pick_objects::RemoveBoxResponse>
{
  static const char* value()
  {
    return DataType< ::pick_objects::RemoveBox >::value();
  }
  static const char* value(const ::pick_objects::RemoveBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_OBJECTS_MESSAGE_REMOVEBOX_H
