(cl:defpackage pick_objects-srv
  (:use )
  (:export
   "PLACEBOX"
   "<PLACEBOX-REQUEST>"
   "PLACEBOX-REQUEST"
   "<PLACEBOX-RESPONSE>"
   "PLACEBOX-RESPONSE"
   "REMOVEBOX"
   "<REMOVEBOX-REQUEST>"
   "REMOVEBOX-REQUEST"
   "<REMOVEBOX-RESPONSE>"
   "REMOVEBOX-RESPONSE"
  ))

